# Generated by Django 3.1.2 on 2020-10-28 12:16

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Large', 'LARGE'), ('Ale', 'ALE'), ('Stout', 'STOUT')], max_length=200)),
                ('country_of_origin', models.CharField(blank=True, choices=[('NP', 'Nepal'), ('IND', 'India')], max_length=100, null=True)),
                ('abv', models.CharField(blank=True, choices=[('Below_10', '>10%'), ('10-20', '10% - 20%'), ('20-40', '20% - 40%'), ('40-60', '40% -  60%'), ('Above 60', '60%<')], max_length=100, null=True)),
                ('brand', models.CharField(blank=True, choices=[('Tuborg', 'TUBORG'), ('Nepal_ice', 'NEPAL ICE')], max_length=100, null=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to=products.models.beer_images)),
            ],
        ),
    ]
